name: mlsdk_flutter_example
description: 迈聆会议 demo
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  mlsdk_flutter: ^1.0.0-beta.3  # 迈聆会议
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0  # 屏幕适配方案
  fluttertoast: ^8.0.7
  dart_jsonwebtoken: ^2.4.2
  flutter_smart_dialog: ^4.5.4+2
  device_info: ^0.4.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/img_create_meeting.png
    - assets/images/home/img_join_meeting.png

